# Generated by Django 4.2.5 on 2023-09-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='aberto',
        ),
        migrations.AddField(
            model_name='loja',
            name='pausado',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
