# Generated by Django 4.2.5 on 2023-09-11 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_preco_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_original',
            field=models.CharField(default='0', max_length=10, validators=[django.core.validators.RegexValidator(message='O valor deve ser um número decimal, que pode conter um ponto ou uma vírgula como separador decimal.', regex='^\\d+(\\.\\d{0,2})?$|^\\d+(\\,\\d{0,2})?$')]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.CharField(default='0', max_length=10, validators=[django.core.validators.RegexValidator(message='O valor deve ser um número decimal, que pode conter um ponto ou uma vírgula como separador decimal.', regex='^\\d+(\\.\\d{0,2})?$|^\\d+(\\,\\d{0,2})?$')]),
        ),
    ]
