# Generated by Django 4.2.5 on 2023-09-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='tipo_culinaria',
            field=models.CharField(choices=[('BR', 'Brasileira'), ('IT', 'Italiana'), ('AM', 'Americana'), ('JP', 'Japonesa'), ('JP', 'mexicana'), ('OU', 'Outra')], default='OU', max_length=2),
        ),
    ]
