# Generated by Django 4.2.5 on 2023-10-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_alter_loja_tipo_culinaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='tipo_culinaria',
            field=models.CharField(choices=[('BR', 'Brasileira'), ('IT', 'Italiana'), ('AM', 'Americana'), ('JP', 'Japonesa'), ('MX', 'Mexicana'), ('OU', 'Outra')], default='OU', max_length=2),
        ),
    ]
