# Generated by Django 4.2.5 on 2023-10-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_alter_loja_tipo_culinaria'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='loja',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lojas.loja'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='prodto_carrinho/%Y/%m'),
        ),
    ]
